/* SAMWEST WHOLESALE DISTRIBUTORS KENYA catalogue */
const samwestProducts = [
{id:101,name:'Eggs Tray',cat:'Dairy',price:350,img:'https://vimandistributors.store/images/WhatsApp-Image-2025-11-20-at-6.58.00-PM-2-1.jpeg'},
{id:102,name:'20 Litres SALIT/BAHARI/POSTMAN/PIKA Cooking Oil',cat:'Cooking',price:3200,img:'https://vimandistributors.store/images/download-66.jpg.jpeg'},
{id:103,name:'10 Litres SALIT/BAHARI/POSTMAN/PIKA Cooking Oil',cat:'Cooking',price:1600,img:'https://vimandistributors.store/images/1q.jpg.jpeg'},
{id:104,name:'20 Litres RINSUN Vegetable Oil',cat:'Cooking',price:3400,img:'https://vimandistributors.store/images/download-67.jpg.jpeg'},
{id:105,name:'SOMO Solid Cooking Fat 10Kg Carton',cat:'Cooking',price:1650,img:'https://vimandistributors.store/images/download-69.jpg.jpeg'},
{id:106,name:'FRYMATE 10kg Carton',cat:'Cooking',price:1350,img:'https://vimandistributors.store/images/download-71-166x300.jpg.jpeg'},
{id:107,name:'25kg BIRIYANI Rice',cat:'Staples',price:1950,img:'https://vimandistributors.store/images/download-7.jpg.jpeg'},
{id:108,name:'25kg BASMATI Rice',cat:'Staples',price:2400,img:'https://vimandistributors.store/images/download-76.jpg.jpeg'},
{id:109,name:'25kg PISHORI Rice',cat:'Staples',price:3200,img:'https://vimandistributors.store/images/download-76.jpg.jpeg'},
{id:110,name:'25kg SINDANO Rice',cat:'Staples',price:1800,img:'https://vimandistributors.store/images/download-7.jpg.jpeg'},
{id:111,name:'50kg SUGAR (Brown)',cat:'Staples',price:5450,img:'https://vimandistributors.store/images/download-76.jpg.jpeg'},
{id:112,name:'50kg SUGAR (White)',cat:'Staples',price:5600,img:'https://vimandistributors.store/images/download-2-1.jpg.jpeg'},
{id:113,name:'WHEAT FLOUR 2kg Bale (Ajab, Pembe, Dola, Ndovu, Soko)',cat:'Staples',price:1800,img:'https://vimandistributors.store/images/images-3-300x150.jpg.jpeg'},
{id:114,name:'WHEAT FLOUR 1kg Bale (Ajab, Pembe, Dola, Ndovu, Soko)',cat:'Staples',price:1750,img:'https://vimandistributors.store/images/download-13g.jpg.jpeg'},
{id:115,name:'MAIZE FLOUR 2Kg Bale (Pembe, Dola, Ndovu, Soko)',cat:'Staples',price:1600,img:'https://vimandistributors.store/images/woocommerce-placeholder.webp'},
{id:116,name:'MAIZE FLOUR 1kg Bale (Pembe, Dola, Ndovu, Soko)',cat:'Staples',price:1550,img:'https://vimandistributors.store/images/m1-300x150.jpg.jpeg'},
{id:117,name:'REDBULL (24 packs)',cat:'Beverages',price:2400,img:'https://vimandistributors.store/images/download-39.jpg.jpeg'},
{id:118,name:'PREDATOR Energy Drink 500ml (12 pcs)',cat:'Beverages',price:550,img:'https://vimandistributors.store/images/download-42.jpg.jpeg'},
{id:119,name:'POWERPLAY Energy Drink 500ml (12pcs)',cat:'Beverages',price:500,img:'https://vimandistributors.store/images/download-3y.jpg.jpeg'},
{id:120,name:'25kg MILK POWDER',cat:'Dairy',price:7800,img:'https://vimandistributors.store/images/download-56.jpg.jpeg'},
{id:121,name:'MENENGAI Bar soap 1Kg (A Carton of 25 pcs)',cat:'Cleaning',price:3000,img:'https://vimandistributors.store/images/download-23.jpg.jpeg'},
{id:122,name:'MSAFI Bar soap 1Kg (10pcs)',cat:'Cleaning',price:1250,img:'https://vimandistributors.store/images/download-25.jpg.jpeg'},
{id:123,name:'BIDCO Cream Bar Soap 800g (25 pieces)',cat:'Cleaning',price:2300,img:'https://vimandistributors.store/images/download-25.jpg.jpeg'},
{id:124,name:'Lato UHT Whole Milk 500ml (Box of 12 pieces)',cat:'Dairy',price:520,img:'https://vimandistributors.store/images/download-38.jpg.jpeg'},
{id:125,name:'Lato PureGEE 1kg (A carton of 12 pieces)',cat:'Dairy',price:4580,img:'https://vimandistributors.store/images/download-38.jpg.jpeg'},
{id:126,name:'Lato BUTTER 500g (A carton of 12 pieces)',cat:'Dairy',price:5880,img:'https://vimandistributors.store/images/download-38.jpg.jpeg'},
{id:127,name:'CHEESE 250g (Box of 12pcs)',cat:'Dairy',price:3600,img:'https://vimandistributors.store/images/download-40.jpg.jpeg'},
{id:128,name:'DAAWAT Spaghetti 400g (A carton of 24 Pieces)',cat:'Staples',price:1150,img:'https://vimandistributors.store/images/21784_main.avif'},
{id:129,name:'Bella/Hanan Tissue (Bale of 48 pieces)',cat:'Cleaning and Hygiene',price:1020,img:'https://vimandistributors.store/images/download-11-1.jpg.jpeg'},
{id:130,name:'Weetabix 45grams (A carton of 24 Pieces)',cat:'Staples',price:1370,img:'https://vimandistributors.store/images/download-1.jpg.jpeg'},
{id:131,name:'INDOMIE 70g (A Carton of 24 Pieces)',cat:'Staples',price:850,img:'https://vimandistributors.store/images/greenspoon_indomie_70g-2076-100x100.jpg.jpeg'},
{id:132,name:'Sunlight Washing Powder 500g (24 Pieces)',cat:'Cleaning and Hygiene',price:2800,img:'https://vimandistributors.store/images/woocommerce-placeholder.webp'},
{id:133,name:'Softcare Pampers (Bale of 6 Packets)',cat:'Health & Beauty',price:3000,img:'https://vimandistributors.store/images/download-4.jpg.jpeg'},
{id:134,name:'Kisskids (Bale of 6 Packets)',cat:'Health & Beauty',price:2400,img:'https://vimandistributors.store/images/download-5.jpg.jpeg'},
{id:135,name:'Molfix (Bale of 6 Packets)',cat:'Health & Beauty',price:2770,img:'https://vimandistributors.store/images/download-4.jpg.jpeg'},
{id:136,name:'Maize 90kg',cat:'Cereals',price:3000,img:'https://vimandistributors.store/images/download-55.jpg.jpeg'},
{id:137,name:'Makueni Ndengu 90kg',cat:'Cereals',price:8300,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:138,name:'Nylon Ndengu 90Kgs',cat:'Cereals',price:7600,img:'https://vimandistributors.store/images/download-54.jpg.jpeg'},
{id:139,name:'Kamande 50kg',cat:'Cereals',price:7000,img:'https://vimandistributors.store/images/download-53.jpg.jpeg'},
{id:140,name:'Livelle Toilet Tissue 10×4s',cat:'Cleaning and Hygiene',price:1500,img:'https://vimandistributors.store/images/download-11-1.jpg.jpeg'},
{id:141,name:'Poshy Roll Xtra Toilet Tissue Unwrapped 4×10s',cat:'Cleaning and Hygiene',price:1000,img:'https://vimandistributors.store/images/download-11-1.jpg.jpeg'},
{id:142,name:'Poshy Mega Tissue Jumbo Roll Wrapped 12×1s',cat:'Cleaning and Hygiene',price:2100,img:'https://vimandistributors.store/images/download-11-1.jpg.jpeg'},
{id:143,name:'Celine Premium Serviettes 12×100 Sheets',cat:'Cleaning and Hygiene',price:900,img:'https://vimandistributors.store/images/download-11-1.jpg.jpeg'},
{id:144,name:'Nuru Scouring Powder Lemon Fresh Bottle 24×500g',cat:'Cleaning and Hygiene',price:1200,img:'https://vimandistributors.store/images/download-30.jpg.jpeg'},
{id:145,name:'Msafi White Bar Soap 12×700g',cat:'Cleaning and Hygiene',price:1500,img:'https://vimandistributors.store/images/download-25.jpg.jpeg'},
{id:146,name:'Nuru Dish Washing Paste Lemon Spark 6×800g',cat:'Cleaning and Hygiene',price:1500,img:'https://vimandistributors.store/images/download-31.jpg.jpeg'},
{id:147,name:'Velvex Dishwashing Liquid Lemon Burst 1×5L',cat:'Cleaning and Hygiene',price:450,img:'https://vimandistributors.store/images/download-30.jpg.jpeg'},
{id:148,name:'Sunlight Hand Washing Powder Eden Yellow 6×1kg',cat:'Cleaning and Hygiene',price:2000,img:'https://vimandistributors.store/images/woocommerce-placeholder.webp'},
{id:149,name:'Vim POWDER Lemon Fresh 6×1kg',cat:'Cleaning and Hygiene',price:1000,img:'https://vimandistributors.store/images/woocommerce-placeholder.webp'},
{id:150,name:'Jik Bleach Regular 4×1.5L',cat:'Cleaning and Hygiene',price:2860,img:'https://vimandistributors.store/images/download-30.jpg.jpeg'},
{id:151,name:'Jik Bleach Colours 4×1.5L',cat:'Cleaning and Hygiene',price:4300,img:'https://vimandistributors.store/images/download-30.jpg.jpeg'},
{id:152,name:'Nuru Dish Washing Liquid Lemon Spark 4×5L',cat:'Cleaning and Hygiene',price:2350,img:'https://vimandistributors.store/images/download-31.jpg.jpeg'},
{id:153,name:'Makueni Ndengu — Price per KG',cat:'Prices per KG',price:95,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:154,name:'Nylon Ndengu — Price per KG',cat:'Prices per KG',price:85,img:'https://vimandistributors.store/images/download-54.jpg.jpeg'},
{id:155,name:'Kamande — Price per KG',cat:'Prices per KG',price:145,img:'https://vimandistributors.store/images/download-53.jpg.jpeg'},
{id:156,name:'Maize — Price per KG',cat:'Prices per KG',price:30,img:'https://vimandistributors.store/images/download-55.jpg.jpeg'},
{id:157,name:'Njahi — Price per KG',cat:'Prices per KG',price:65,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:158,name:'Yellow Beans — Price per KG',cat:'Prices per KG',price:85,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:159,name:'Wairimu Beans — Price per KG',cat:'Prices per KG',price:65,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:160,name:'Nyayo Beans — Price per KG',cat:'Prices per KG',price:65,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:161,name:'Rosecoco — Price per KG',cat:'Prices per KG',price:70,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'},
{id:162,name:'Pigeon Peas/Bhaazi — Price per KG',cat:'Prices per KG',price:75,img:'https://vimandistributors.store/images/download-52.jpg.jpeg'}
];

/* Replace the old Viman catalogue with the SAMWEST catalogue. */
products.length = 0;
samwestProducts.forEach(product => products.push(product));
localStorage.removeItem('vimanCart');
cart.length = 0;
if (typeof renderCategories === 'function') renderCategories();
if (typeof renderProducts === 'function') renderProducts();
if (typeof renderCart === 'function') renderCart();